version: "3.8"

services:
  handbrake-server:
    image: handbrake-server
    container_name: handbrake-server
    ports:
      - 5100:5100
    volumes:
      - ./config:/usr/src/handbrake-server/config
      - ${HB_HOST_JOB_DIR:-./jobs}:${HB_JOB_DIR:-/jobs}
      - ${HB_HOST_MEDIA_DIR:-./media}:${HB_MEDIA_DIR:-/media}
    restart: unless-stopped
